[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 